spring.application.name=psiconotes
spring.datasource.url=jdbc:postgresql://ep-holy-art-ac3w2yhs-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_X4xyUMY6ftcN&sslmode=require&channelBinding=require
#spring.datasource.username=postgres
#spring.datasource.password=gabryel54
spring.jpa.hibernate.ddl-auto=update
server.port=1509
server.address=0.0.0.0
#para exibir o trace no console usar o GET /tabela?trace=true
#server.error.include-stacktrace=on_param
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true